### ISSUE TITLE
部分补充和修改

### ISSUE THREAD

**Issue by Charley-Hsu** [yihong0618/dalian-IT#3]
**外包补充**
华钦软件
华录

**本地企业**
大商天狗在裁员，快黄了。
腾讯无线，实际叫世纪鲲鹏
大连飞创 是国企，大商所技术公司
加一个大商所飞泰  是飞创分出来，专业测试公司
加一个 众安科技

**外企**
IBM 刚裁员
甲骨文 快没了吧
罗克斯韦尔  应为  罗克韦尔
富达 男性也有六个月陪产假
英特尔在开发区

**其他**
华录的总部在大连，大央企，不能一概而论
东软也是，不同部门差距很大。不是单纯的外包

**Comment by yihong0618** [comment]
@Charley-Hsu 感谢，可以提个`PR` 如果你感兴趣的话。

**Comment by Charley-Hsu** [comment]
@yihong0618  您可以再组织一下页面结构呢，比如加上公司网站，主营业务，现状等等。我给您pr补充材料。不打乱您的布局和结构

**Comment by yihong0618** [comment]
可以啊，你有兴趣都可以增加，我目前精力有限，对很多公司也没那么了解，如果你有更多想法的话，我可以把你加上合作者，不知道你有兴趣加入么？

**Comment by Charley-Hsu** [comment]
> 可以啊，你有兴趣都可以增加，我目前精力有限，对很多公司也没那么了解，如果你有更多想法的话，我可以把你加上合作者，不知道你有兴趣加入么？

可以 我时间还可以，比较充裕

**Comment by yihong0618** [comment]
@Charley-Hsu 邀请你了。感谢。
